name: Backend CI CD

on:
  push:
    branches:
      - main
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Docker hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devroutine .

      - name: Docker hub publish
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/devroutine

      - name: Run application use SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          username: ubuntu
          host: ${{ secrets.WAS_HOST }}
          key: ${{ secrets.WAS_KEY }}
          script: |
            sh /home/ubuntu/deploy.sh
